### ISSUE TITLE
get websocket server in gedis to run through flask so we only have 1 port

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_weblibs#1]
![image](https://user-images.githubusercontent.com/6021844/43367723-28d44264-9352-11e8-8091-93532746f1a7.png)

**Comment by arahmanhamdy** [comment]
fixed https://github.com/threefoldtech/jumpscale_lib/commit/f93f4e39b6f87f1c106d2ff581c367e66af48edf
